# Site settings
title: Shaswat Gupta
header-img: img/forest.jpg
email: shagup770@gmail.com
description: "3rd year Under Graduate Student in Information Technology at National Institute of Technology,Durgapur India"
baseurl: ""
url: "http://nishatshirin/shaswatgupta.github.io"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 15

# Gems
gems: [jekyll-paginate]

localhost: 8000
